parameters:
    php_mag_ecb.httpclient.class: Guzzle\Http\Client
    php_mag_ecb.parser.class:     KIJ\Bundle\EcbBundle\Ecb\Parser

services:
    php_mag_ecb:
        class: %php_mag_ecb.httpclient.class%

    php_mag_ecb.parser:
        class: %php_mag_ecb.parser.class%
