parameters:
    kij_ecb.httpclient.class: Guzzle\Http\Client
    kij_ecb.parser.class: KIJ\Bundle\EcbBundle\Ecb\Parser
    kij_ecb.adapter.class: KIJ\Bundle\EcbBundle\Ecb\Adapter
    kij_ecb.adapter.endpoint: http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
    kij_ecb.rates.class: KIJ\Bundle\EcbBundle\Ecb\ExchangeRates

services:
    kij_ecb.httpclient:
        class: %kij_ecb.httpclient.class%

    kij_ecb.parser:
        class: %kij_ecb.parser.class%
        public: false

    kij_ecb.adapter:
        class: %kij_ecb.adapter.class%
        arguments:
        - @kij_ecb.httpclient
        - %kij_ecb.adapter.endpoint%

    kij_ecb.rates:
        class: %kij_ecb.rates.class%
        arguments:
        - @kij_ecb.adapter
        - @kij_ecb.parser
        public: false

    ecb.rates:
        alias: kij_ecb.rates
